### ISSUE TITLE
[BUG]The program turns off when the game starts

### ISSUE THREAD

**Issue by LetItBe22** [floh22/LeagueBroadcastHub#147]
**Describe the bug**
It's okay up to Ban Pick,
but the program turns off when the game starts

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 20H1 (May 2020 Update) Build 19041]

**Additional context**
[Crash-2022-05-09-16-04.log](https://github.com/floh22/LeagueBroadcast/files/8649454/Crash-2022-05-09-16-04.log)
[Log-2022-05-09-16-01.log](https://github.com/floh22/LeagueBroadcast/files/8649455/Log-2022-05-09-16-01.log)

**Comment by floh22** [comment]
`[WARNING] LeagueBroadcast not enabled in live game. Stopping game connection`

This line in the config indicates you were trying to run the program over a live game instead of a replay. I'm going to assume it actually was a replay due to the following line:

`[WARNING] Could not parse game config. Replay API may not be enabled!`

This means your game config couldnt be parsed. Mind sharing it? it should be in `League of Legends/Config/game.cfg`. One thing that might be the issue is line endings. Try to see if your line endings are `CR LF`. If not, you can change those in a program like Notepad++
