### ISSUE TITLE
Could not read all data from memory champions. Submit an issue in github containing the current record and playback

### ISSUE THREAD

**Issue by Laceleague** [floh22/LeagueBroadcastHub#149]
Hi! I have a problem with my program.I think there will be new patch. Good day and help me please!

![163236599-bc349f49-826d-4d46-89d0-414ed1c1c281](https://user-images.githubusercontent.com/105067114/168279158-e8316a29-a583-4312-96dd-62458dd90628.png)

**Comment by Ons1992** [comment]
Hi there, I do also have the same issue.

Since patch day the Memory reading is not functioning. 
This has been tested in two devices. 

On Windows 10 the score-bar shows but it does not work as intended.

On a Windows 11 machine the program crashes/disappears  as soon as the game starts.

Thanks for your hard work!

**Comment by Laceleague** [comment]
Sisi, no funciona y nosotros los realizadores lo hemos probado y no va esperemos que se solucione pronto es el cambio de parche estoy casi seguro.

**Comment by bwims91** [comment]
Same here, looking forward to a fix!

**Comment by DreadpoolDDG** [comment]
Same issue here

**Comment by Coow** [comment]
Hi! @floh22 has pushed the Offsets, this should work now
