### ISSUE TITLE
how can i use this progame in two computer?

### ISSUE THREAD

**Issue by miki98703** [floh22/LeagueBroadcastHub#152]
I'm trying to broadcast in two computer now. 
 how can i use this program when i stream?

**Comment by FireFoXz09** [comment]
As far as i know, the program wasn't made for this purpose. (Single PC with League of Legends, League Broadcaster and OBS running).

I did find a turnaround tho for this on a remote production I had to do a few weeks ago by using the "Preview Projector" function of OBS to preview on another screen the game and the League Broadcast overlay, then "Screen Sharing" this screen to the PC that broadcast (with PARSEC for example). It wasn't perfect but for a remote production i made the job. For a Dual PC Stream setup, you could just capture the screen with the preview. (Running OBS on the Gaming PC to have a preview of the overlay, without streaming, and cature this on the second PC and use OBS on this one to stream the result.)

**Comment by floh22** [comment]
The webserver hosted by LeagueBroadcast should be available to the outside network. In your LAN you should be able to access the websites or API by using the local address of the PC hosting LeagueBroadcast. Outside of your local network you would have to port forward or similar since your local PC is acting as a server host. Either this or @FireFoXz09 solution should both be viable ways to adapt to a 2 PC solution
