### ISSUE TITLE
Broken Offsets 12.10.1 [BUG]

### ISSUE THREAD

**Issue by Laceleague** [floh22/LeagueBroadcastHub#155]
Hi! I have a problem with my program.I think there will be new patch. Good day and help me please!

**Comment by Laceleague** [comment]
I need help

**Comment by Laceleague** [comment]
Hi! I have a problem with my program.I think there will be new patch. Good day and help me please!

**Comment by Laceleague** [comment]
![168279158-e8316a29-a583-4312-96dd-62458dd90628](https://user-images.githubusercontent.com/105067114/170365963-6a6aabcf-68bd-4390-95b3-6d9cb254359d.png)

**Comment by FireFoXz09** [comment]
This is not a bug but it's only because the offsets of the new patch haven't been updated yet on the League Broadcast software. It takes usually 1 or 2 days (usually done the friday) to update manually by **floh22**.

Usually you should be able to still use the program, but some feature can bug or not work properly. Just wait a day or two and it should be done :)

**Comment by Grayknife** [comment]
I leave not working features on patch 12.10.1 as a comment here: 
- Only the CS per Minute Graph seems to be working correctly
- Item/Levelup Notifications do not working
- EXP and Gold Tab do not open (after opening cs/min, this tab will be opened even if gold or exp tab are clicked)
- Goldgraphs shows an empty graph

I do not use other features, but there could be more bugs.

I will check it again within the next two days :)

**Comment by floh22** [comment]
Because of an oversight, some offsets were not updated after the latest patch. 

**If you have already started LeagueBroadcast after 12.10.1 and are now running into issues, delete `Config/Farsight.json` before starting the program.** 

At some point in the future I will add an ability to hotfix offsets in cases like this
