### ISSUE TITLE
[Improvement] Automatic offsets - is there a way?

### ISSUE THREAD

**Issue by MDvorky** [floh22/LeagueBroadcastHub#176]
Can we somehow make uploading offsets more automatic? 
Is there a way?

**Comment by MDvorky** [comment]
Or just show us how to do, so we can make it by ourselves - leave tutorial or some guide to it. Please :D I have all my graphic based on this app to work @floh22

**Comment by floh22** [comment]
You could update the program to use patterns instead of offsets directly, since those change far less frequently, but this would be a rather large undertaking and require extensive knowledge of the League codebase, or rather a good bit of experience in IDA.
I sadly do not have the time to do this, and barring unforeseen illness or similar, updating takes between 5-30 minutes every two weeks, not justifying tons of development time, at least for me
