### ISSUE TITLE
[BUG] Cannot read data

### ISSUE THREAD

**Issue by AzureAstral** [floh22/LeagueBroadcastHub#179]
Hello, 

I have a tournament (partner with RIOT GAMES) this week-end and the progam said "Cannot read data" ... Gold dont update, etc...

Plz I need help ! It's really important !

Thx 🙏

**Comment by Coow** [comment]
If it for live, follow these instructions :
https://github.com/floh22/LeagueBroadcast/issues/175#issuecomment-1193292378

If its for tournament realm:
Unfortunately the memory mappings for the Tournament Realm is different than Live. So all Ingame Memory Reading functions, like gold graph, wont work.

**Comment by AzureAstral** [comment]
It's for live.

But it's work for 12.14 ? He was release yesterday

**Comment by Coow** [comment]
You would have to wait for @xTrimy to make new offsets then

**Comment by AzureAstral** [comment]
Ok so i need to wait @floh22 or @xTrimy make new offsets...? No solution ?

**Comment by AzureAstral** [comment]
Really no solution ? I really need it T_T

**Comment by MDvorky** [comment]
You can generate offsets by yourself - but it is little bit complicated :) or you have to wait.

**Comment by AzureAstral** [comment]
How i can generate offsets ?

**Comment by AzureAstral** [comment]
No information ? :/

**Comment by JoanJuan10** [comment]
There is no clear information on how to generate those offsets since those change from version to version. To know about them you may need to ask the creator of this repo.

For now what I would do is wait for this to update when he heals up or take a look at the forks of this project, since other people are already trying to generate those offsets.
