### ISSUE TITLE
Working together with the RCVolus?

### ISSUE THREAD

**Issue by Freeedooo** [floh22/LeagueBroadcastHub#220]
Hey @floh22 ,
did you think about working together with the Riot Community Volunteers? They are from Germany as well and seem to have issues with the memory reading in their production toolkit. Since they have a web interface which you don't have that one might be a useful cooperation, wouldnt it?

Regards
Fredo

**Comment by floh22** [comment]
This project actually started as a fork of their work before I decided to attempt my own version. Back then their toolkit was only focused on champ select and their planned architecture for ingame required each player to install software on their local computer. This works for them since they are a closed small league and can guarantee that their software will be installed on each players PC. 

However, I find this approach to the architecture fundementally flawed for any sort of widespreach useable spectate tool, so I haven't looked into their work further since then. The increased complexity + distribution of software to all players is something I do not think is viable for a widely used tool. + all information you could want is right there on the spectate PC, you just have to get it. If they reach out I will of course help where I can, and they are more than welcome to use source code from this project in their own, thats the beauty of open source

**Comment by Freeedooo** [comment]
That’s in fact not the case. Have a new, closer look. You don’t need to install it on all player pcs just on the spectator ones.Isn‘t that better then?

In my opinion your tool is the perfect addition to their work or vice versa. I got to love your work so I think their tool is the perfect addition. But I am not a programmer just an enthusiast and a broadcast professional.

**Comment by overkido** [comment]
@floh22 
would you be able to add additional functions, we need some additional things for the championship and I would like to know if you add the function in a specific way that you sell the version like a prize for less amateur champions for example, would you sell the additional functions or an app new with the functions it already has plus the additional ones we would ask for?

**Comment by floh22** [comment]
> That’s in fact not the case. Have a new, closer look. You don’t need to install it on all player pcs just on the spectator ones.Isn‘t that better then? In my opinion your tool is the perfect addition to their work or vice versa. I got to love your work so I think their tool is the perfect addition. But I am not a programmer just an enthusiast and a broadcast professional.

Interesting. I haven't had a look since then, and honestly this project is in somewhat of a maintenancemode while I finish my masters, but I will for sure have a look and see where one might be able to integrate the two and how much work that would be

**Comment by floh22** [comment]
> @floh22 would you be able to add additional functions, we need some additional things for the championship and I would like to know if you add the function in a specific way that you sell the version like a prize for less amateur champions for example, would you sell the additional functions or an app new with the functions it already has plus the additional ones we would ask for?

unrelated. also no. I have a job and am studying, so I dont have the time.

**Comment by Freeedooo** [comment]
I would love to see a cooperation. In the meantime I try to implement the best of both worlds :D
