### ISSUE TITLE
[Issue] TR offsets different to live patch

### ISSUE THREAD

**Issue by Tortron1** [floh22/LeagueBroadcastHub#231]
Describe the bug
LeagueBroadcast doesnt pick up the existence of the Tournament Realm Client.
If I install the normal client it works.
I tried to rename the folder, add \\ at the end of the LeagueInstall and reinstalling both the Broadcaster and the client.

To Reproduce
1. Launch LeagueBroadcast with Tournament Realm Client installed
2. The application gives an error
![image](https://user-images.githubusercontent.com/112067017/221853417-7f6e6bce-21c8-4c5b-970a-dd4ffef188af.png)

Expected behavior
The Tournament Realm Client is recognized as a valid League install

Material
![image](https://user-images.githubusercontent.com/112067017/221853699-5007d009-d321-42e1-a650-8251817d2834.png)
![image](https://user-images.githubusercontent.com/112067017/221854114-6f857885-5b85-4301-8a1e-d714a6b19c2e.png)

[Log-2023-02-28-13-23.log](https://github.com/floh22/LeagueBroadcast/files/10850213/Log-2023-02-28-13-23.log)

**Comment by Freeedooo** [comment]
Hey @Tortron1 ,
is it possible to post the results of your testing here (or reach out to me) since I am very interested in them.

Regards,
Fredo

**Comment by Tortron1** [comment]
> 

@Freeedooo, I'm using version 1.6.50, but the results of my testing are that pointing to the exact map where Riot Games is in, or pointing directly to the tournament realm install doesn't seem to make a difference. One interesting this is that when I had the regular client and the tournament realm client installed at the same time the program would still give the "no client found" error, but it still connected to the normal client. 
Here are also the crash logs that I genereated during my testing and my latest regular log. 
 
[Crash-2023-02-28-11-36.log](https://github.com/floh22/LeagueBroadcast/files/10868992/Crash-2023-02-28-11-36.log)
[Crash-2023-02-28-11-47.log](https://github.com/floh22/LeagueBroadcast/files/10868993/Crash-2023-02-28-11-47.log)
[Crash-2023-02-28-11-56.log](https://github.com/floh22/LeagueBroadcast/files/10868994/Crash-2023-02-28-11-56.log)
[Log-2023-03-02-09-16-0.log](https://github.com/floh22/LeagueBroadcast/files/10869013/Log-2023-03-02-09-16-0.log)

**Comment by Ayvanm** [comment]
i also been trying to use it on the tournament servers but i wouldnt show up the gold, cs/min, level up, items etc. It could connect to the client but wont show this things.

**Comment by Coow** [comment]
League Broadcast does find the Tournament Realm installs and connects just fine. This is since the API is the same.
The issue is however with read the memory from the TR Spectator Client, since there is a vast difference between that and the Live Spectator Client. 

TR would need seperate Memory Mappings/Offsets for each Server, aka all 6. I think in theory this is because of the extra offset that the Banners create in the Client. I haven't had the time to test the theory out. 

If you want to try to create Offsets there is documentation for how to do that here: https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight
Although there will probably be some extra knowledge and tinkering to get it working with TR

**Comment by floh22** [comment]
That assesment sounds in line with what people are experiencing, though the cannot detect league install is another issue.

Sadly since I do not have access to the TR, I cannot provide offsets. 

In the future the best solution would probably be to automatically detect the TR realm and use appropriate offsets, for now though, if anyone does create the offsets, I would recomend creating a separate repo and hosting the offsets there, and changing the repo in the configs
