### ISSUE TITLE
[BUG] Urgent! Overlay app is crashing even after updating offsets

### ISSUE THREAD

**Issue by Honzalis** [floh22/LeagueBroadcastHub#245]
![obrazek](https://user-images.githubusercontent.com/91389306/227973958-75287906-3d69-4503-a278-1c359f10e267.png)

I have 2 issues. One is the first picture. I tried updating the farsight file with the data that one of the users posted here but i got the new message, that the champion data could not be loaded. App did not crash but bothing was showing in the browser.

![obrazek](https://user-images.githubusercontent.com/91389306/227975284-d5603aac-62f6-48b0-886a-5217456d50b2.png)

here are the logs
[Crash-2023-03-27-16-39.log
[Log-2023-03-27-16-44.log](https://github.com/floh22/LeagueBroadcast/files/11079930/Log-2023-03-27-16-44.log)
](https://github.com/floh22/LeagueBroadcast/files/11079927/Crash-2023-03-27-16-39.log)

I would be glad if the previous version would be working, but it won't load. We relied on this app for our tournament stream so we would need this to work urgently please.

**Comment by neeemo** [comment]
A lot of people having the same problem, any help would be gladly appreciated!

**Comment by FireFoXz09** [comment]
I managed to make it work by modifying the farsight file.

Paste this in the Farsight.json file :

> {
>   "OffsetVersion": "13.6.2",
>   "GameOffsets": {
>     "Manager": "0x186E154",
>     "MapCount": "0x2c",
>     "MapRoot": "0x28",
>     "MapNodeNetId": "0x10",
>     "MapNodeObject": "0x14"
>   },
>   "ObjectOffsets": {
>     "ID": "0x8",
>     "NetworkID": "0xb4",
>     "Team": "0x34",
>     "DisplayName": "0x54",
>     "DisplayNameLength": "0x64",
>     "Pos": "0x1dc",
>     "Mana": "0x029C",
>     "MaxMana": "0x2ac",
>     "Health": "0xe7c",
>     "MaxHealth": "0xe8c",
>     "CurrentGold": "0x1bb4",
>     "GoldTotal": "0x1bc4",
>     "EXP": "0x32ec",
>     "Name": "0x2b04"
>   },
>   "FileVersion": "2.0"
> }

**Comment by neeemo** [comment]
I already tried the 0x186E154 as the Manager. Still no luck for me, my log says

[04-10-51] [WARNING] Lissandra not found in memory snapshot. Values will be incorrect!
[04-10-51] [WARNING] Sequence contains no matching element
[04-10-51] [WARNING] Nunu & Willump not found in memory snapshot. Values will be incorrect!
[04-10-51] [WARNING] Leona not found in memory snapshot. Values will be incorrect!
[04-10-51] [WARNING] Ornn not found in memory snapshot. Values will be incorrect!
[04-10-51] [WARNING] Tristana not found in memory snapshot. Values will be incorrect!
[04-10-51] [WARNING] Maokai not found in memory snapshot. Values will be incorrect!
[04-10-51] [WARNING] Xerath not found in memory snapshot. Values will be incorrect!
[04-10-51] [WARNING] Zilean not found in memory snapshot. Values will be incorrect!

Otherwise everything else is working fine. :(

**Comment by FireFoXz09** [comment]
I'll do more test monday. Be sure to change the others information too as the offsets weren't good for me in 3 or 4 places.

**Comment by neeemo** [comment]
Thanks FireFox! At the moment I can use the RCVolus prod toolkit for the live games, but it doesn't work with replays, so there is where League Broadcast is invaluable for me. I tried copying in the whole offsets you gave me, but still giving me the errors as above. I been trying to create my own offsets as well, but I'm not really that good at it yet.

**Comment by FireFoXz09** [comment]
Strange, I tested yesterday with a replay file and it worked... 

As said, I'll do more testing monday. I'm away from my PC for the weekend.

**Comment by neeemo** [comment]
Yeah seems to be something with the offsets since the VCVolus League Prod Toolkit is having the same problem, and they have ongoing issues there as well mentioning that the memory reading functionality isn't working and is likely cause of offsets!

**Comment by loverlsp** [comment]
0x186E154 as the Manager, works

**Comment by neeemo** [comment]
That is indeed strange, since a lot of others are having the Champions cannot load problem. What other could it be?

**Comment by neeemo** [comment]
Alright I just tried to use 0x186E154 and it just started working. I am 100% sure I tried this 100 times, so something must have happened. But anyway works for me now.
