### ISSUE TITLE
[BUG] Scoreboard Popup

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#60]
working until 2nd baron appear

it doesn't popup on 2nd baron appear and it appear after 60secs
and after that blue and red team each have 2 stack of dragon and blue just killed dragon and that make 3 dragon but the soul point popup 
and next dragon popup after 21secs and next baron popup appear after 66secs
[Log-2021-08-08-15-34-0.log](https://github.com/floh22/LeagueBroadcast/files/6951437/Log-2021-08-08-15-34-0.log)
[Log-2021-08-08-15-34.log](https://github.com/floh22/LeagueBroadcast/files/6951438/Log-2021-08-08-15-34.log)

https://youtu.be/P_NrSzswCN8?t=1611

baron popup not appear

https://youtu.be/P_NrSzswCN8?t=1674

baron popup appear after 60secs

https://youtu.be/P_NrSzswCN8?t=1760

mountain draon appear
and killed and shown soul point at 3rd dragon

**Comment by FireFoXz09** [comment]
I've also noticed the "Soul Point" at the 3rd dragon. Not sure if it's a bug or if it's programmed to tell us that the next dragon gonna be soul point for a team. I would prefer a different announce if a team kill the 4th dragon, and get the soul (instead of announcing that the next dragon could be the soul, or maybe both, actually!)

**Comment by EagleLOL** [comment]
Hey I'm having the same problem. The baron spawn works for the first baron at 20.00 but other baron spawns are bugged. Sometimes they appear a minute later sometimes they don't even appear.
