### ISSUE TITLE
[BUG] Failure to generate graphics

### ISSUE THREAD

**Issue by VermilionRose** [floh22/LeagueBroadcastHub#80]
**Description**
Graphics fail to generate on both pick-ban and in-game browser pages

**To Reproduce**
1. Working with the 1.4.97 release, download and extract to desired install folder (in my case, my Desktop)
2. Open Application LeagueBroadcast
3. Open League of Legends client and confirm "Client Connected" at the top of the Appliction
4. Open http://localhost:9001/?backend=ws://localhost:9001/api (pick-ban) and http://localhost:9001/frontend?backend=localhost (in-game)
5. Create custom Draft Mode game, add bots, and start Champ Select
6. Graphics on pick-ban browser page fail to generate

**Expected behavior**
Expect to see a champion pick-ban graphic
Tested within Tournament Draft, Draft Mode and on Chrome, OBS, and MS Edge

**Material**
Log file and screenshot:
[Log-2021-10-05-00-55.log](https://github.com/floh22/LeagueBroadcas
![Screenshot (17)](https://user-images.githubusercontent.com/83625427/135963200-58d45fff-d989-48c9-b280-5b462e3afadc.png)
t/files/7282865/Log-2021-10-05-00-55.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19043 Build 19043
.

**Comment by VermilionRose** [comment]
Update on the issue. Graphics generate on the InGame scene using a Replay file

**Comment by FireFoXz09** [comment]
Yes because (if I'm not wrong), the LeagueBroadcast software won't work if YOU are in a game. You need to be a SPECTATOR for it to activate. If not, the memory reading could get you banned by the anti-cheat system of League of Legends.

First chapter of the description how to use it SAYS IT 

"**Anti Cheat does not ban for programs used during spectate, but it does however run while in a live game. Having League Broadcast open during a live (non-spectate) game may lead to account bans incase checks to stop it from running fail for some reason.**"

![image](https://user-images.githubusercontent.com/89284738/136086358-f4d4f6a9-e0a7-44da-aba5-d95560fcb81e.png)

**Comment by VermilionRose** [comment]
I did just test it as a Spectator in a custom Tournament Draft lobby with a friend and 9 bots and it also didn't work unfortunately yet this could be just because the software perhaps doesn't work with bots. Anyways, the RCVolus Pick/Ban package DOES work when I myself am within the champ select as a player and not a spectator with as many bots as I want. As I noted above in my edit, the Ingame graphic works within a Replay file yet the Pick/Ban graphic continues to not with myself as a spectator

**Comment by FireFoXz09** [comment]
It's because the League Broadcast is made to not run except if you are in a game / draft as a Spectator, to prevent the anti-cheat system of LoL to detect it and ban you (during the game, not during the pick/ban phase). The RCVolus Pick/Ban only affect the draft, but the LeagueBroadcast software won't activate (thus won't activate the RCVolus pick/ban package) except if you are a Spectator.

Tho I did not try with bots, but every drafts I spectated worked first try. For easiest test, just ask a friend to do a draft without bots and go spectator. Enven with only one player this should start the RCVolus Pick/Ban. Or go find a custom game and spectate it. You can also spectate a friend who just started a game. (if you spectate his game before the 3 minute mark, you'll see the draft and the RCVolus Pick/Ban draft should open/start.)

I'll run some test with a fresh install of the 1.4.97 version tonight to see if I can replicate your problem.

**Comment by floh22** [comment]
Can you try opening the browser console window and see if events are received by the frontend? If it does receive events, can you expand and post an event received during active pickban/ingame?

That aside, and about the other topics brought up in this issue: There might be an issue with bots, though I thought I fixed that, I havent had the time to verify that recently. Try a lobby with a single player or no bots, it will still work if you are actively in the lobby and not spectating

PickBan **DOES** work if you are not spectating. The readme is intentionally left rather vague to discourage use in non spectate games, as I really don't want people to try and use this in a live game. Only the ingame component is disabled in a live game. In the future, messaging and documentation will be more clear about all this, it just hasnt bee an priority yet.

**Comment by gboero00** [comment]
Hey everyone! 
I'm having the same issue as well. LeagueBroadcast is running as administrator but the website is a blank page.
Here's a console screenshot: https://i.ibb.co/dfs7RFg/Screenshot-4.png

I tried it earlier this week and worked just one time, i believe it's casual. We organize tournaments so we can't use this overlay unless it works every single time.

Thanks!

**Comment by VermilionRose** [comment]
I just realized that I need this issue to close. The pick-ban does work when I'm a spectator.
