### ISSUE TITLE
[BUG] Champion Select (RCVolus PickBan Tools) won't start

### ISSUE THREAD

**Issue by FireFoXz09** [floh22/LeagueBroadcastHub#85]
**Describe the bug**
Sometimes, when the draft begin (pick/ban phase), the RCVolus Tool won't start. Happened to me like 3 times yesterday during a tournament. 

**Issue**
I think it's related to the time it takes to start the lobby maybe? (sometimes waiting 15-20 minutes in the lobby before starting) Or because of the Riot API? (It's been buggy/glitchy since the last patch). To be clear, before the last LoL patch (patch 11.21), everything worked properly and without any issues.

I'll do more tests during the week. I do this post to keep track of any finds or clues.

**Comment by floh22** [comment]
I have also noticed inconsistencies with the LCU after the chromium update to the league client on some setups, though I have not been able to determine exactly what is causing the issue.

Even then, it does not explain your issue of it having worked flawlessly the patch prior, and only becoming an issue now, considering the chromium update happened a few patches ago. I may need to look at the LCU library I am using, to see if the issue might be caused due to it, or rather if the issue can be solved by a library change.

**Comment by FireFoXz09** [comment]
Yeah it's strange. I reopened my client today and restarted League Broadcast, started a custom game and the Pick/Ban started as expected. I closed the League Broadcast program and restarted it to try something and no pick-ban in a brand new custom game. Seems to be "random" but there is certainly something off somewhere. (League Broadcast does detect the LoL client since I see the "Client Connected" in the software when I log in)

**Comment by shinilee** [comment]
I'm pretty sure I had this bug too I also had just client bug if I stay in the custom lobby long time and when the game start I can't connect into the game and if someone invite me into the custom game and sometime I get ingame error so I just create the room when players are ready

**Comment by FireFoXz09** [comment]
> I'm pretty sure I had this bug too I also had just client bug if I stay in the custom lobby long time and when the game start I can't connect into the game and if someone invite me into the custom game and sometime I get ingame error so I just create the room when players are ready

Yesterday samething, the Pick/Ban do not start if I've been for too long in the lobby (more than 3-5 minutes it seems). But it worked when I joined it right before they started the draft. Since it's a tournament code and the teams want to get in the lobby before doing the prodraft or other setup, I can't create the lobby myself to invite them at the last minute so I need them to invite me right before starting.

Strange issue tho, the in-game scoreboard bugged yesterday, it couldn't read the memory info (the timer was frozen to 00:43 IGT for exemple). I had to restart the LeagueBroadcast twice to get it work. (While I was spectating). It crashed too while trying to read/show the gold diff graph (at the 45 minute mark IGT)

**Comment by shinilee** [comment]
I just test now the pickban ui doesn't work and when i leave the pickban client the program close itself

**Comment by shinilee** [comment]
I test today just now and the pick/ban doesn't work at all it only work when I make a custom game and start the game just myself in it no player, no bot then it work but it doesn't work with bot and doesn't work with player in it when I test and I just test with 10 players as I'm spectator doesn't work

**Comment by floh22** [comment]
I cannot reproduce this issue, it seems to be an issue of the league client itself. Have you tried a different PC or restarting? I cannot reproduce this issue on 3 separate PCs after both restarts and reinstalls, so im having a hard time tracking the source

**Comment by shinilee** [comment]
if you can't reproduce this issue with 3 separate PCs and I tried with 2 different pcs and I ask others to tried with they are pcs and it only gives the issue I think it's from the custom build from me I will try to download fresh and will test it and let you know

**Comment by shinilee** [comment]
I just download fresh and didn't change anything and it doesn't work for me. I tested 3

1. create custom game myself and start the game and it work.
2. create custom game and add 9 bots and start the game and it doesn't work
3. invite 10 people and start the game and it doesn't work

**Comment by FireFoXz09** [comment]
Yeah I dunno why samething for me. Sometimes it works, sometimes it won't start. Just really strange...

Ill run the original RCVolus PickBan on the side at the same time to see if it works all the time too and let you know.

**Comment by floh22** [comment]
Since I cannot currently seem to replicate this issue, the most useful thing for me is if someone with general coding knowledge opens the project in Visual Studio and runs the program in Debug mode through Visual Studio. Then my debugging approach would be as follows:

1. Check if the entered champ select message appears in logs, make sure logging is set to verbose. If it does not, add breakpoint at https://github.com/floh22/LeagueBroadcast/blob/1f3898691dd9990f2acb02fdf0a045ffe5b09119/LeagueBroadcast/Common/Controllers/AppStateController.cs#L171
See if this gets called. If it does not when you enter champ select, then the library I use for getting data from the client is the issue and im going to have to do some research as to why it is behaving that way. This is the most important info for me atm, since I do not know where the issue originates.

If it is the case it is called, please let me know, because then I have to change the flag system that determines what state the client is in, something I think would be the cause of the issue if it is not the LCU connection

**Comment by FireFoXz09** [comment]
They updated the requied Node.js version for running the program. Can this be the solution? (I'm gonna give it a try this weekend)

Updated november 24 on the RCVolus PickBan Tools page:
> Download and install Node.JS for Windows (or any other operating system): https://nodejs.org/download/release/v16.7.0/node-v16.7.0-x64.msi (please really install the linked version, 16.7.0, **as otherwise you may run into issues**)
