### ISSUE TITLE
[BUG] Viego transform triggers item buy

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#86]
everytime viego transform to enemy champion the item appear. not big of issue tho... the big issue is the ban pick doesn't work :(

**Comment by FireFoXz09** [comment]
For Viego, it's been like this since I can remember (since the game reads it as having new items in the inventory.) Just strange at first but not sure you can correct this easily...

The pick/ban bugs for me as well. I need to "delete" all the pickban folder in the frontend section and recreate it (copy it elsewhere -> delete it from the frontend folder -> replace it) to make it work. Also, don't stay in a lobby for too long, it bugs the pickban and won't start it.

**Comment by shinilee** [comment]
tried to delete the folder and copy and paste it but it doesn't work for me

**Comment by floh22** [comment]
Viego is indeed a bug.

Please keep issues separate so they are easier to track

**Comment by Grayknife** [comment]
Viego bug is still present :(
