### ISSUE TITLE
[BUG] The icon of the dragon does not work

### ISSUE THREAD

**Issue by Nezumi2711** [floh22/LeagueBroadcastHub#92]
The icon of dragon on the scoreboard is not show after the team slay them. How can I fix it? I have restart many time the LeagueBroadcast when in spectator but still not work.

LeagueBroadcast v1.4.106

**Comment by FireFoXz09** [comment]
There's already a topic about this issue : https://github.com/floh22/LeagueBroadcast/issues/89

**Comment by Nezumi2711** [comment]
> There's already a topic about this issue : #89

No, I meant the icon of dragon like this:
![image](https://user-images.githubusercontent.com/73208452/143251664-a6f3907b-9db6-4f81-b765-a9f638644447.png)

**Comment by FireFoXz09** [comment]
All the dragons icons won't show? Or only the new dragons (hextech/chemtech) ? Does it show a black square like on the picture?
![image](https://user-images.githubusercontent.com/89284738/143260639-adf082b6-1cfb-485c-8040-c0f0b16f9b98.png)

If you restart the LeagueBroadcast WHILE you spectate a game, the dragons won,t show until the program "see" a team kill a dragon (if you join a game where they already have killed a dragon, it won't show it on the scoreboard) since it's memory reading, it update when an event happen, not if an event already happened.

If this is not the case, try deleting everything and reinstall the new version of LeagueBroadcast in another folder on your PC maybe?

**Comment by Nezumi2711** [comment]
All the dragon icons won't show.
I have try reinstall and use another device to test it but it still not work. I have open the LeagueBroadcast during the team slay Dragon. Maybe I have not edited somewhere in config file?

**Comment by FireFoXz09** [comment]
Strange. Try running it as an admin. LeagueBroadcast bugged for me monday but yesterday all my "bugs" went away and the program was working totally fine. Maybe a glitch or something... I'll check this out tonight on my side.

**Comment by Nezumi2711** [comment]
I always run program as an admin, it will crashed if I don't run. I hope you can help me. Thanks!

**Comment by Nezumi2711** [comment]
> Strange. Try running it as an admin. LeagueBroadcast bugged for me monday but yesterday all my "bugs" went away and the program was working totally fine. Maybe a glitch or something... I'll check this out tonight on my side.

Can you share your config file ingame so i can refer?

**Comment by ghost** [comment]
I have solve my problem by follow this comment. 
https://github.com/floh22/LeagueBroadcast/issues/8#issuecomment-839817187

I will close topic, thanks for help!
